# Generated by Django 5.2.3 on 2025-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('INVESTMENT', 'Investment Inquiry'), ('TENANCY', 'Tenancy Inquiry'), ('GENERAL', 'General Inquiry'), ('MEDIA', 'Media Inquiry'), ('OTHER', 'Other Inquiry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('INVESTOR', 'Investor'), ('GOVERNMENT', 'Government Agency'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
