# Generated by Django 5.2.3 on 2025-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='color_type',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GREEN', 'Green'), ('BROWN', 'Brown')], default='null', max_length=20),
        ),
    ]
