# Generated by Django 5.2.3 on 2025-06-27 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homehero_color_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickstat',
            name='description',
            field=ckeditor.fields.RichTextField(default='none'),
        ),
    ]
