# Generated by Django 5.2.3 on 2025-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_quickstat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickstat',
            name='icon',
        ),
        migrations.AddField(
            model_name='quickstat',
            name='icon_type',
            field=models.CharField(choices=[('COMPANY', 'bi bi-building'), ('LAND SIZE', 'bi bi-map'), ('JOBS', 'bi bi-briefcase')], default='null', max_length=20),
        ),
    ]
