# Generated by Django 5.2.3 on 2025-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_quickstat_icon_quickstat_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickstat',
            name='icon_type',
            field=models.CharField(choices=[('COMPANY', 'bi bi-building'), ('LAND SIZE', 'bi bi-map'), ('JOBS', 'bi bi-briefcase')], default='COMPANY', max_length=20),
        ),
    ]
