# Generated by Django 5.2.3 on 2025-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_quickstat_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickstat',
            name='icon_type',
            field=models.CharField(choices=[('bi bi-building', 'Company'), ('bi bi-map', 'Land Size'), ('bi bi-briefcase', 'Jobs')], default='COMPANY', max_length=20),
        ),
    ]
