# Generated by Django 5.2.3 on 2025-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_quickstat_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
