# Generated by Django 5.2.3 on 2025-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_is_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
    ]
