# Generated by Django 5.2.3 on 2025-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_aboutsection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='icon_type',
            field=models.CharField(choices=[('bi bi-building', 'Park'), ('bi bi-map', 'Land Size'), ('bi bi-briefcase', 'Jobs')], default='Park', max_length=20),
        ),
    ]
