# Generated by Django 5.2.3 on 2025-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_aboutsection_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='icon_type',
            field=models.CharField(choices=[('bi bi-building', 'Park'), ('bi bi-bullseye', 'Mission'), ('bi bi-eye-fill', 'Vision')], default='Park', max_length=20),
        ),
    ]
