# Generated by Django 5.2.3 on 2025-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_aboutsection_icon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
