# Generated by Django 5.2.3 on 2025-06-27 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_teammember_bio_alter_teammember_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('fas fa-bolt fa-3x mb-3', 'Power Supply'), ('fas fa-tint fa-3x mb-3', 'Water System'), ('fas fa-trash-alt fa-3x mb-3', 'Waste Management')], default='Park', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
