# Generated by Django 5.2.3 on 2025-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_infrastructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='icon_type',
            field=models.CharField(choices=[('fas fa-bolt fa-3x mb-3', 'Power Supply'), ('fas fa-tint fa-3x mb-3', 'Water System'), ('fas fa-trash-alt fa-3x mb-3', 'Waste Management')], default='Power Supply', max_length=100),
        ),
    ]
