# Generated by Django 5.2.3 on 2025-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_infrastructure_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='icon_type',
            field=models.CharField(choices=[('fas fa-bolt', 'Power Supply'), ('fas fa-tint', 'Water System'), ('fas fa-trash-alt', 'Waste Management')], default='Power Supply', max_length=100),
        ),
    ]
