# Generated by Django 5.2.3 on 2025-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_infrastructure_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_type',
            field=models.CharField(choices=[('bi bi-building', 'Business Facilities'), ('bi bi-people', 'Support Services'), ('bi bi-wallet', 'Investment Opportunities'), ('bi bi-gem', 'Golden Investment Opportunities')], default='Business Facilities', max_length=100),
        ),
    ]
