# Generated by Django 5.2.3 on 2025-06-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_service_icon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
