# Generated by Django 5.2.3 on 2025-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('FACILITY', 'Business Facilities'), ('SUPPORT', 'Support Services'), ('INVESTMENT', 'Investment Opportunities'), ('GOLDEN', 'Golden Investment Opportunities')], default='Golden Investment Opportunities', max_length=20),
        ),
    ]
