# Generated by Django 5.2.3 on 2025-06-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_contactsubmission_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(choices=[('INVESTMENT', 'Investment Inquiry'), ('TENANCY', 'Tenancy Inquiry'), ('GENERAL', 'General Inquiry'), ('MEDIA', 'Media Inquiry'), ('OTHER', 'Other Inquiry')], max_length=20),
        ),
    ]
