# Generated by Django 5.2.3 on 2025-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_newsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('TENANT', 'Tenant'), ('INVESTOR', 'Investor'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
