# Generated by Django 5.2.3 on 2025-07-01 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_title', models.CharField(blank=True, max_length=100)),
                ('tenant_company', models.CharField(blank=True, max_length=100)),
                ('testimonial_type', models.CharField(choices=[('QUOTE', 'Text Quote'), ('VIDEO', 'Video Testimonial')], default='QUOTE', max_length=5)),
                ('quote', models.TextField(blank=True, help_text='The testimonial text content')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='testimonials/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])])),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonials/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Testimonial',
                'verbose_name_plural': 'Tenant Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='testimonial',
        ),
    ]
