# Generated by Django 5.2.3 on 2025-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_testimonial_remove_partner_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='partner',
            name='testimonial',
            field=models.TextField(blank=True),
        ),
    ]
