# Generated by Django 5.2.3 on 2025-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_delete_testimonial_partner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Golden Opportunity', max_length=255)),
                ('grace_period_years', models.PositiveIntegerField(default=2)),
                ('down_payment_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('installment_count', models.PositiveIntegerField(default=2)),
                ('exclusive_benefits', models.TextField()),
                ('strategic_advantages', models.TextField()),
                ('location_highlights', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
