# Generated by Django 5.2.3 on 2025-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_goldenopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenopportunity',
            name='down_payment_percentage',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=5),
        ),
    ]
