# Generated by Django 5.2.3 on 2025-07-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_goldenopportunity_down_payment_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='testimonial',
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('PARTNER', 'Partner'), ('TENANT', 'Tenant'), ('INVESTOR', 'Investor'), ('OTHER', 'Other')], default='PARTNER', max_length=20)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_title', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField(blank=True, help_text='The testimonial text content')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='website.partner')),
            ],
            options={
                'verbose_name': 'Tenant Testimonial',
                'verbose_name_plural': 'Tenant Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
