# Generated by Django 5.2.3 on 2025-07-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_partner_testimonial_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='partner_type',
        ),
    ]
