# Generated by Django 5.2.3 on 2025-07-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_remove_testimonial_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
