# Generated by Django 5.2.3 on 2025-07-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_testimonial_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='ManagementTeam',
        ),
    ]
