# Generated by Django 5.2.3 on 2025-07-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_rename_teammember_managementteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='tenant_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='tenant_title',
        ),
    ]
