# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_remove_testimonial_tenant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='manager_role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Director', 'Director'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
