# Generated by Django 5.2.3 on 2025-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_testimonial_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='manager_role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Director', 'Director'), ('Other', 'Other')], default='', max_length=10),
        ),
    ]
