# Generated by Django 5.2.3 on 2025-07-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_resourcecategory_faq_downloadable_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldenopportunity',
            name='location_highlights',
        ),
    ]
