# Generated by Django 5.2.3 on 2025-07-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_remove_goldenopportunity_location_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldenopportunity',
            name='down_payment_percentage',
        ),
        migrations.RemoveField(
            model_name='goldenopportunity',
            name='grace_period_years',
        ),
        migrations.RemoveField(
            model_name='goldenopportunity',
            name='installment_count',
        ),
    ]
