# Generated by Django 5.2.3 on 2025-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_announcement_docs_announcement_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
