# Generated by Django 5.2.3 on 2025-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_alter_announcement_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_type',
            field=models.CharField(choices=[('bi bi-building', 'Business Facilities'), ('bi bi-people', 'Support Services'), ('bi bi-wallet', 'Investment Opportunities')], default='Business Facilities', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('FACILITY', 'Business Facilities'), ('SUPPORT', 'Support Services'), ('INVESTMENT', 'Investment Opportunities')], default='Golden Investment Opportunities', max_length=20),
        ),
    ]
