# Generated by Django 5.2.3 on 2025-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_service_icon_type_alter_service_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('hours', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
